name: Python Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Run Python Script
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install MetaTrader5
        pip install torch
        pip install torchvision torchaudio
        pip install pytest

    - name: Run pytest
      run: pytest
